### ISSUE TITLE
1 - Display the list of boulders on "Find my Boulder" page

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#1]
## Value statement - a requirement, not a solution
As a climber
I want to retrieve a list of active boulders  
so that I can find a specific boulder

## Description (Text, Scribble, Wireframe, Design)

<img width="323" alt="Screenshot 2022-04-26 at 13 32 05" src="https://user-images.githubusercontent.com/94105745/165290868-ff8e692b-80eb-4477-a123-52a62d23bd42.png">

## Acceptance criteria
- [ ] when the frontend starts, a hardcoded list of boulders are rendered as a list of cards
- [ ] The boulder list includes at least the following boulder details:
- [ ] ID
- [ ] Name
- [ ] Level
- [ ] Handle color
- [ ] Sector
- [ ] Likes
- [ ] Weighting

## Tasks

- [ ] Set up "Find my boulder" page on front end, including suitable header.
- [ ] Create boulder component which will display the mentioned information as a card
- [ ] Create a basic styling for the boulder card
- [ ] Add test case for boulder card (to check if the information are displayed)

## Size
medium
