### ISSUE TITLE
Save climbed boulder form entry to database

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#10]
## Value statement - a requirement, not a solution
As a climber
I want my "add climbed boulder form" entry to be saved in a db
so that this is accessible from anywhere.

## Description (Text, Scribble, Wireframe, Design)

The following is an example of how the climbed_boulder object looks like and should be saved to the db:

{ id: "999999", climber_id: "9999999999", boulder_id: "3", date: Date Mon May 02 2022 10:16:38 GMT+0200 (Central European Summer Time), projected: false, attempts: "4", result: "top", liked: true, level_feedback: 0 }

## Acceptance criteria
- [ ] When the climber clicks on the save button the user will either get a confirmation that the data was saved to the db or
- [ ] There is an error message in case something went wrong with saving the data.
- [ ] On the "Add" page the saved data will be shown within the confirmation to the climber.

## Tasks
- [ ] set up collection "climbed_boulder"
- [ ] implement POST route to save new documents "climbed_boulder" to the db.
- [ ] make sure that a POST which belongs to a climbed_boulder document of a the user for the same boulder gets updated rather than additionally created
- [ ] use the response from the backend with the new entry to show it below the form on the "add" page

## Size
(medium)

**Comment by PReichetanz** [comment]
Looks really good to me!

There is one thing which came to my mind regarding task 3 (and I think this is because I don't really understand yet how your app is going to work):
I see that you want to make sure that there are no duplicated entries, but updating an entry in a DB is normally a Patch request, isn't it? I would suggest to outsource the Patch into another story and only write the Post request here. You can still tell the user that the data was not stored because there already exists similar data.

Besides, I had a look at your current Vercel deployment: Is the database really the most important thing you need to add right now (as soon as you have created the two pages "find" and "add my boulder")? Or are there other things the user needs to do with your app? If so, the database can wait and you could use localStorage instead.

**Comment by PulexIrritans** [comment]
@PReichetanz 
I Paul, thank you for your feedback. I'm not sure how I can do it with PATCH/ POST based on the two different scenarios. I think the Save button should  only trigger one action, so either POST or PATCH. However if it is really a new entry, then it must be a POST, right? If it's an update I thought I could implement the respective logic in the backend and use the same route (POST)?

Also, yes. I think the time has come to do some work on the backend. As I want to use the climbed_boulder entries to work with the data (e.g. aggregate etc.) and then provide some stats etc to the user. If I do it only with local storage first it will be much harder to implement and later on I would have to set it up in the backend again. I can't see what the advantage would be here...
