### ISSUE TITLE
9 - Filter boulder list

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#16]
## Value statement - a requirement, not a solution
As a climber 
I want to filter the boulder list 
so that I can find a specific boulder more easily

## Description (Text, Scribble, Wireframe, Design)
<img width="235" alt="Screenshot 2022-05-05 at 15 23 58" src="https://user-images.githubusercontent.com/94105745/167510090-9bd83bd1-5660-4218-a682-6edb0916ad04.png">

## Acceptance criteria
- [x] There is a filter for "level"
- [x] There is a filter for "sector"
- [x] There is a filter for "hold color"
- [x] All of those filters are dropdowns
- [x] The climber can select from one of the dropdowns to filter the boulder list by one criterion.
- [x] The boulder list will update showing only the boulders that match the selected criterion.

## Tasks
- [x] implement a dropdown field for each of the above three filters
- [x] The available dropdown values should match the respective boulder property values:
- [x] boulders.hold_color
- [x] boulders.level
- [x] boulders.sector
- [x] render the boulder cards based on the selected filter

## Size
(medium)

**Comment by PReichetanz** [comment]
Hey Antje,
looks really good so far!

I just have three questions (maybe I ask some of them just to make sure that you have already thought about every detail but did not write them down 😉):

1. When exactly will the results of your filter be displayed - as soon as the user chose at least one filter or as soon as he/she clicks the (scribbled, but not mentioned) search button?
2. What is displayed if there are no results? Is it possible for this case to occur?
3. How do you get to this filter page and how do you navigate back to your home page? Does a navigation (or just Link elements) already exists and you can adjust it?
