### ISSUE TITLE
10 - Overall climbs by boulder level

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#20]
## Value statement - a requirement, not a solution
As a climber
I want to see the stats of the boulders I climbed by level
so that I can be proud of how many hard boulders I have climb.

## Acceptance criteria
- [ ] On the main page there is a visualization of the boulders climbed by boulder level.
- [ ] The chart will update automatically when the climber adds a new climb via the form.

## Tasks
- [ ] Implement an api route which fetches the climbed boulders for a climber by boulder level.
- [ ] Implement a chart component and hand over the fetched values.
- [ ] 

## Size
(medium)
