### ISSUE TITLE
11 - Dynamic boulder pictures

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#21]
## Value statement - a requirement, not a solution
As a climber
I want to see a unique picture for every boulder 
so that I can use the image to identify the correct boulder on the boulder club

## Acceptance criteria
- [ ] Each boulder card contains an image of the start holds of the respective boulder at the short version of the boulder card (which is shown on the "Find" page.
- [ ] As a nice to have the detailed boulder card version shows a picture of the entire boulder route.

## Tasks
- [ ] use the file names for the start picture and the file name of the picture for the entire route from the respective boulder document to dynamically generate the picture.
- [ ] upload the boulder picture to the project

## Size
(medium)
