### ISSUE TITLE
12 - Improve Style of climbed boulder form

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#22]
## Value statement - a requirement, not a solution
As a  climber
I need a boulder form which is styled for the needs of a mobile phone 
so that I can easily enter my climber boulder data during the boulder session.

## Acceptance criteria
- [ ] The radio buttons appear as buttons I can tap.
- [ ] The check boxes are big enough to be checked nicely on a mobile phone
- [ ] As a nice2have the number input field has the option to be used like a counter (+/-)

## Tasks
- [ ] update the styling of the form component

## Size
(medium)
