### ISSUE TITLE
13 - Display number of likes based on actual db values

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#23]
## Value statement - a requirement, not a solution
As a climber  
I want to see that the likes of the boulders increase by one if I like a boulder
so that I can see which boulders have been liked by many climbers.

## Acceptance criteria
- [ ] When the climber checks the "liked" checkbox in the boulder form the number of likes in the boulder card will be increased by one.
- [ ] However each boulder can be liked only once by a climber.

## Tasks
- [ ] Fetch the number of likes from the backend when generating the boulder cards.
- [ ] Save the number of likes in a use state so that the card will always be rendered with the current likes value.

## Size
(medium)
