### ISSUE TITLE
Display a club ranking on the main page

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#24]
## Value statement - a requirement, not a solution
As a climber 
I want to see the club rankings
so that I can be competitive.

## Acceptance criteria
- [ ] On the main page there is a list which shows the top five climbers of the boulder club.

## Tasks
- [ ] Implement a list with climber user name and total points ordered as a ranking.
- [ ] The ranking represents the points gained by each climber compared to other climbers.
- [ ] Difficult boulders have a higher weighting than easier boulders. And therefor the climber earns more points by topping or flashing a harder boulder.
- [ ] Points per boulder: Sum of all Boulders weighting * 1 (for top) or Boulder weighting*2 (for flash)

## Size
(medium)
