### ISSUE TITLE
16 - Display day count since last boulder session

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#26]
## Value statement - a requirement, not a solution
As a climber
I want to see how many days have past since my last boulder session
so that I gain more motivation to have the next one

## Acceptance criteria
- [ ] On the main page an information is displayed of how many days have past since the last boulder session. 

## Tasks
- [ ] Implement a component to display the day counter
- [ ] Implement a data fetch in the new front-end component to get the date of the latest boulder session
- [ ] Implement an api route that finds the latest climbed_boulder date for the climber end sends it to the front end.

## Size
small
