### ISSUE TITLE
2 - Detailed view of Boulder Card

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#3]
## Value statement - a requirement, not a solution
As a climber
I want to select a specific boulder by clicking on a button "climb"  
so that a more detailed view of the boulder card is shown

## Description (Text, Scribble, Wireframe, Design)
<img width="202" alt="Screenshot 2022-04-27 at 16 16 11" src="https://user-images.githubusercontent.com/94105745/165539311-ff554d24-550d-44ee-abf7-e68222c97845.png">

## Acceptance criteria
- [ ] By clicking on the button "Climb" the boulder card extents and holds additional information as follows:
- [ ] Tags (which represent "technical requirements" of the boulder route)
- [ ] Setter name
- [ ] Weighting (used for calculation of rankings)

The button "climb" is not present anymore when the detailed view is shown

## Tasks
- [ ] Implement a detailed version of the Boulder Card component including the additional above information
- [ ] Implement a useState for the Boulder Card which is used to control which version is shown
- [ ] The useState should change from detailedMode = false to detailedMode = true on button "Climb" click

## Size
smedium
