### ISSUE TITLE
17 - Climbs of last boulder session

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#33]
## Value statement - a requirement, not a solution
As a climber
I want to see an overview of all climbs of my latest boulder session
so that I know what exactly I did within the session

## Description (Text, Scribble, Wireframe, Design)
<img width="611" alt="Screenshot 2022-05-11 at 09 10 43" src="https://user-images.githubusercontent.com/94105745/167790324-775b672a-6f53-4f72-8c9a-2088bc3fd669.png">

## Acceptance criteria
- [ ] On the main page there is a chart displaying the total climbs of the latest boulder session
- [ ] The chart does also reveal the results for the climbs: Flash/ Top/ Zone/ Just touched

## Tasks
- [ ] Add a session stats component
- [ ] Fetch the session stats from the backend
- [ ] Add an api route to the backend which finds the latest session date and takes this to filter all climbed_boulders with this date
- [ ] Then calculate the total results from these filtered climbed_boulders and send them as a response

## Size
(medium)
