### ISSUE TITLE
18 - Level feedback indicator on boulder cards

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#34]
## Value statement - a requirement, not a solution
As a climber
I want to see if a boulder is considered much harder/ much easier than the level would suggest
so that I have a second information (besides level) about how hard a boulder is actually

## Acceptance criteria
- [ ] On the boulder card there is a red arrow pointing to top if the boulder has a level feedback greater than or equal to 3.
- [ ] On the boulder card there is a blue arrow pointing to bottom if the boulder has a level feedback lower than or equal to -3.
- [ ] On the boulder card there is a yellow arrow pointing to the right if the boulder has a level feedback between 2 and -2.

## Tasks
- [ ] In the backend add the logic to calculate the sum of all level feedbacks of each boulder and add the information to the response for the boulder fetch
- [ ] In the front end add the arrows as above to the short version of the boulder cards.

## Size
(medium)
