### ISSUE TITLE
19 - "Completed boulder" indicator on Find page.

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#35]
## Value statement - a requirement, not a solution
As a climber
I want to quickly see when I already have completed a boulder
so that I can focus on the boulders I haven't completed yet. 

## Acceptance criteria
- [x] On the find page all boulder cards from boulders I have already completed have a different color or an additional icon (find what looks good).

## Tasks
- [x] In the backend add a logic to the boulder-fetch which will add the information if a boulder has a climbed_boulder entry for the respective user. And return the information when the boulder list is fetched for the user.
- [x] In the frontend use the information if the boulder was completed to style the boulder card with another background color.

## Size
(medium)
