### ISSUE TITLE
20  - Firebase Login

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#36]
## Value statement - a requirement, not a solution
As a climber
I have to login to the app
so that I can see my unique data and nobody else's and nobody can access my data.

## Description (Text, Scribble, Wireframe, Design)
<img width="492" alt="Screenshot 2022-05-11 at 20 24 56" src="https://user-images.githubusercontent.com/94105745/167919998-fd3b1094-aa54-4adb-a574-18171f04eea8.png">

## Acceptance criteria
- [ ] There is the firebase default login page 
- [ ] Only after successful login the user can access the content of the app with his own data
- [ ] The app will display the correct user data

## Tasks
- [ ] Implement the firebase login based on the following video tutorial and documentation
- [ ] https://www.youtube.com/watch?v=PKwu15ldZ7k&t=455s
- [ ] https://firebase.google.com/docs/web/setup?authuser=0&hl=de
- [ ] use the authentication information from firebase to display user specific data (to be used when fetching)

## Size
(large)
