### ISSUE TITLE
21 - Filter boulders by projected true

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#37]
## Value statement - a requirement, not a solution
As a climber
I want to filter my projected boulders
so that I can find them easily 

## Acceptance criteria
- [ ] On the find page there is a toggle button (type checkbox) to filter the projected boulders

## Tasks
- [ ] Add a checkbox and style it as a toggle button
- [ ] In the backend add logic to get the projected info for the user from the climbed_boulders and add this to the boulder GET route for the user
- [ ] use the projected information in the boulder objects to filter the boulder list if filtered by "projected"

## Size
(medium)
