### ISSUE TITLE
3 - New page "Add my climbed boulder"

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#4]
## Value statement - a requirement, not a solution
As a climber
I want to enter the data for a climbed boulder in a form 
so that  these can be used to calculate rankings and stats.

## Acceptance criteria

- [ ] The form includes the following input fields:
- [ ] Date (default selection is current date, but this can be changed)
- [ ] Projected (Checkbox)
- [ ] Attempts (Number)
- [ ] Zone/ Top/ Flash (Radio Button)
- [ ] Level Feedback - Too easy/ Just right / Too hard (Radio Button)
- [ ] Like (Checkbox)
- [ ] Save Button (type Submit)

None of the fields is required however at least one input must have been changed in order to enable the submit button. 
The form should also have a validation so that the user can only enter the required data types.

## Tasks
- [ ] Set up the form with the fields that are listed above.
- [ ] Set up useStates in order to save and display the entered data.
- [ ] Set up a useState for the Button state (enabled/ disabled)
- [ ] Implement a logic to enable the button only when one of the input useStates has changed

## Size
(medium)

**Comment by mbosselmann** [comment]
Hey Antje,

I like your user story! 👍  It is a large and you can think about making implementing the navigation as extra user story, but that is your choice. I have one remark and one question.

I will start with the question:
Will you add a **wireframe** to your **description** to visualize your feature? 🤔 

And my remark:

'None of the fields is required however at least one input must have been changed in order to enable the submit button.
The form should also have a validation so that the user can only enter the required data types.'
--> These don't have checkboxes yet. Is this intended?

**Comment by PulexIrritans** [comment]
Hi Mareike @mbosselmann , thank you for your question and your remark. I totally forgot the wireframe. This and the missing checkboxes where not intended.
I would prefer to have the navigation within this user story. I think I can implement the whole thing tomorrow. However, please tell me if you as coaches prefer that I separate them. I understand that I shouldn't overload you with one pull request...

**Comment by mbosselmann** [comment]
Hi Antje, 
we coaches don't prefer one option. :) I just suggested to extract the navigation if you want to reduce your story, because the navigation is one component for its own with testing and storybook that could be easily separated in an own user story.
But decide it for yourself. :)
