### ISSUE TITLE
22 - Additional filter for climb results on find page

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#41]
## Value statement - a requirement, not a solution
As a climber
I want to filter the boulder list by my climb result
so that a can select boulders by climb result/ status more easily

## Acceptance criteria
- [ ] There is a dropdown selection on the find page for the climb results
- [ ] The climb results have the categories: Flash, Top, Zone, Touched, None
- [ ] By selecting one of the options the list of boulder cards will only show the cards appropriate to the selection.

## Tasks
- [ ] Add climb results to the filter get route in the backend end api
- [ ] Add climber's climb result information to the boulder list
- [ ] Add filter use states and logic with the climb result selection

## Size
(medium)
