### ISSUE TITLE
22 - Save filter in sessionStorage

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#42]
## Value statement - a requirement, not a solution
As a climber
I want the filter I used to be saved 
so that whenever I come back to the find page my latest filter selection will still be active.

## Acceptance criteria
- [ ] When the climber sets a filter this filter is saved in sessionStorage.
- [ ] When the climber returns to the find page the latest filter selection will be selected still.
- [ ] The filter selection is set to default when entering the page anew.

## Tasks
- [ ] Save filter selection to sessionStorage
- [ ] Get filter selection from sessionStorage on page load
- [ ] Filter boulder list according to filter selection.

## Size
(medium)
