### ISSUE TITLE
Navigation between "Find my boulder" and "Add my climbed boulder"

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#5]
## Value statement - a requirement, not a solution
As a climber
I want to navigate between the two pages "Find my boulder" and "Add my climbed boulder"
so that I can go back to the boulder list after having entered climb data for a specific boulder.

## Acceptance criteria
- [ ] A navigation at the bottom of the page is visible with the two pages "Find my boulder" and "Add my climbed boulder".
- [ ] The climber can click either on the "Climb" button in the boulder list to get to the "Add my climbed boulder" page or in the respective button in the navigation.
- [ ] The climber can get to the "Add my climbed boulder" page via the navigation in the footer.
- [ ] A headline for the two pages is shown in the header of the page.

## Tasks
- [ ] Implement a footer component with a navigation
- [ ] Implement a header component which shows the specific header

## Size
medium

**Comment by PReichetanz** [comment]
"...I want to navigate between the two pages "Find my boulder" and "Add my climbed boulder"
so that I can go back to the boulder list after having entered climb data for a specific boulder."

Just to be sure: Does it matter whether you have added climb data? I guess the navigation link should always work, so I think you can delete the last part ("after having...") because it can create confusion.

Background: What happens if you enter data, but you do not click the submit button, but the "find my boulder" navigation link?  The data is gone, right? I just don't see the relationship between entering data and using the navigation, but I don't think it changes anything you want to do with this story.

**Comment by PulexIrritans** [comment]
@PReichetanz 
Hi Paul, thank you for your comment. I have updated the user story and hope that it is more clear now. I have also added a scribble as this was missing before.
