### ISSUE TITLE
Combine Filter

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#57]
## Value statement - a requirement, not a solution
As a climber
I want to apply mutliple filters when I search for a specific boulder
so that can find it more easily.

## Description (Text, Scribble, Wireframe, Design)

The diifferent filter options should not work separately from each other but rather be possible to be combined. In order to implement this there is no change needed for the user interface. However the logic for the filter needs to be refactored.

## Acceptance criteria
- [ ] When setting one of the filter options there is no effect on the other filters. Their filter selection stays as is.
- [ ] The filter results are all those boulders that meet the criteria of all set filter options combined.

## Tasks
- [ ] Change the onChange event for the filter selection so that only the specific filter is set and no other filter options are touched.
- [ ] Change the filterBoulder function so that the filter selections are checked with AND operator rather than OR.

## Size
(small)
