### ISSUE TITLE
(Short name)

### ISSUE THREAD

**Issue by m4xnull** [PulexIrritans/Heelhook-Capstone#59]
## Value statement - a requirement, not a solution
As a climber
I want to be able to add boulders that aren't in the database, yet,
so that I can log all my climbs and keep route data updated. 

## Acceptance criteria
- [ ] navigation offers a feature for adding a boulder
- [ ] added boulder can be found using the search function
- [ ] attempts and results are stored for the new boulder

## Tasks
- [ ] form for adding boulder
- [ ] add to navigation
- [ ] add entry to database
- [ ] find a way to add images
- [ ] change image retrieval for existing boulders to new approach

## Size
medium

**Comment by PulexIrritans** [comment]
I'm done with this issue. Will create a pull request now, @m4xnull . :-)
