### ISSUE TITLE
Move image storage to cloud/db

### ISSUE THREAD

**Issue by m4xnull** [PulexIrritans/Heelhook-Capstone#60]
## Value statement - a requirement, not a solution
As a developer
I want to retrieve boulder images from a centralized storage like cloud service or database
so that we are able to allow user photos for boulders in a later step.

## Acceptance criteria
- [ ] images are retrieved from centralized storage
- [ ] local boulder image folder is obsolete

## Tasks
- [ ] identify possible storage, e.g. cloud storage or database that allows image objects
- [ ] adapt image link in database for existing boulders
- [ ] adapt image components to new retrieval method

## Size
medium
