### ISSUE TITLE
Allow user images when adding new boulders

### ISSUE THREAD

**Issue by m4xnull** [PulexIrritans/Heelhook-Capstone#61]
## Value statement - a requirement, not a solution
As a climber
I want to be able to add my own image when adding a new boulder
so that boulders are easier to recognize on find page.

## Acceptance criteria
- [ ] user images can be added when adding a boulder
- [ ] user images are displayed on find page for the respective boulders

## Tasks
- [ ] extend add boulder form/section to allow adding images
- [ ] upload user images to image storage
- [ ] retrieve user images from storage when showing boulders on find page

## Size
large
