### ISSUE TITLE
Quickly selecting ex. sectors when adding boulder

### ISSUE THREAD

**Issue by m4xnull** [PulexIrritans/Heelhook-Capstone#62]
## Value statement - a requirement, not a solution
As someone adding a boulder (climber/route setter)
I want to be able to quickly select existing sectors instead of typing every time
so that the process is quicker (and not annoying)

## Description (Text, Scribble, Wireframe, Design)
I have some design ideas but I don't want to disturb the creative process so I'll spare it for now.

## Acceptance criteria
- [ ] offer existing sectors for quick selection
- [ ] still be able to type a sector name, especially when adding boulders in previously unknown sectors

## Tasks
- [ ] change text input to sth. more elaborate
- [ ] pre-fill with existing sectors
- [ ] tbd.

## Size
medium
