### ISSUE TITLE
5 - Set up boulders in database 

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/Heelhook-Capstone#9]
## Value statement - a requirement, not a solution
As a developer
I want to save all boulders in a database 
so that these can be fetched as a complete list by the frontend.

## Description (Text, Scribble, Wireframe, Design)

Each boulder  should be saved as a document in the collection boulders in the mongodb as per the following example:

{
    "id": "1",
    "name": "King Kong",
    "sector": "Monkey Island",
    "level": "1",
    "hold_color": "yellow",
    "setter": "Nora Born",
    "tags": [],
    "img_start": "King_Kong_start.jpg",
    "img_complete": "King_Kong.jpg",
    "weighting": 100,
    "start_date": "2022-05-20",
    "expiry_date": ""
  }

## Acceptance criteria
- [ ] At the page "Find" the boulders list is fetched from the db.
- [ ] All boulders that are present in the boulders db collection are being rendered on the find page.

## Tasks
- [ ] set up mongodb atlas
- [ ] upload boulders (as json) to collection boulders
- [ ] connect backend server with mongodb
- [ ] setup API key in env. file and make sure it's ignored by github
- [ ] set up GET route on backend server to fetch boulders from db on incoming fetch request
- [ ] implement fetch for boulders list on frontend (find page)

## Size
(medium)

**Comment by mbosselmann** [comment]
Hi Antje,
I like your user story. 👍 My remarks:

I think you could write your value proposition also from a user perspective. Suggestion:

**As a** user
**I want to** save my data in a database
**to be able to** access my data from anywhere.

I would add under **acceptance criteria** that if there is no data in your database, the user gets a hint. And for **tasks** I would add error handling. :)

**Comment by PulexIrritans** [comment]
@mbosselmann 
Hi Mareike, thank you for your feedback. I have updated the user story accordingly.
